### ISSUE TITLE
system language detection not working

### ISSUE THREAD

**Issue by theMomax** [veecue/GroupMatcher#6]
The system language detection does not work on my pc (win 10 64-bit). It returns an empty string.

**Comment by rossmeier** [comment]
I added a CLI-Flag `-lang` to select the language through a windows shortcut

**Comment by theMomax** [comment]
Thanks ! Could you please provide an example shortcut and push your work ?

**Comment by theMomax** [comment]
I changed the default to english and added the examples for english and german myself.
